package site.luoyu.dao.mapper;

import site.luoyu.dao.entity.BookTypeinfo;

public interface BookTypeinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_typeinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer booktypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_typeinfo
     *
     * @mbggenerated
     */
    int insert(BookTypeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_typeinfo
     *
     * @mbggenerated
     */
    int insertSelective(BookTypeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_typeinfo
     *
     * @mbggenerated
     */
    BookTypeinfo selectByPrimaryKey(Integer booktypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_typeinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BookTypeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_typeinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BookTypeinfo record);
}