package site.luoyu.dao.mapper;

import site.luoyu.dao.entity.BookComment;

public interface BookCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_comment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_comment
     *
     * @mbggenerated
     */
    int insert(BookComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_comment
     *
     * @mbggenerated
     */
    int insertSelective(BookComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_comment
     *
     * @mbggenerated
     */
    BookComment selectByPrimaryKey(Integer cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BookComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(BookComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BookComment record);
}