package site.luoyu.dao.mapper;

import site.luoyu.dao.entity.UserStudent;

public interface UserStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_student
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer stuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_student
     *
     * @mbggenerated
     */
    int insert(UserStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_student
     *
     * @mbggenerated
     */
    int insertSelective(UserStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_student
     *
     * @mbggenerated
     */
    UserStudent selectByPrimaryKey(Integer stuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_student
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_student
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserStudent record);
}