package site.luoyu.dao.entity;

import java.util.Date;

public class BookIsbn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_isbn.ISBN_id
     *
     * @mbggenerated
     */
    private Long isbnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_isbn.isbn10
     *
     * @mbggenerated
     */
    private String isbn10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_isbn.isbn13
     *
     * @mbggenerated
     */
    private String isbn13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_isbn.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_isbn.image
     *
     * @mbggenerated
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_isbn.author
     *
     * @mbggenerated
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_isbn.translator
     *
     * @mbggenerated
     */
    private String translator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_isbn.publisher
     *
     * @mbggenerated
     */
    private String publisher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_isbn.pubdate
     *
     * @mbggenerated
     */
    private Date pubdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_isbn.binding
     *
     * @mbggenerated
     */
    private String binding;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_isbn.price
     *
     * @mbggenerated
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_isbn.pages
     *
     * @mbggenerated
     */
    private Short pages;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_isbn.ISBN_id
     *
     * @return the value of book_isbn.ISBN_id
     *
     * @mbggenerated
     */
    public Long getIsbnId() {
        return isbnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_isbn.ISBN_id
     *
     * @param isbnId the value for book_isbn.ISBN_id
     *
     * @mbggenerated
     */
    public void setIsbnId(Long isbnId) {
        this.isbnId = isbnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_isbn.isbn10
     *
     * @return the value of book_isbn.isbn10
     *
     * @mbggenerated
     */
    public String getIsbn10() {
        return isbn10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_isbn.isbn10
     *
     * @param isbn10 the value for book_isbn.isbn10
     *
     * @mbggenerated
     */
    public void setIsbn10(String isbn10) {
        this.isbn10 = isbn10 == null ? null : isbn10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_isbn.isbn13
     *
     * @return the value of book_isbn.isbn13
     *
     * @mbggenerated
     */
    public String getIsbn13() {
        return isbn13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_isbn.isbn13
     *
     * @param isbn13 the value for book_isbn.isbn13
     *
     * @mbggenerated
     */
    public void setIsbn13(String isbn13) {
        this.isbn13 = isbn13 == null ? null : isbn13.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_isbn.title
     *
     * @return the value of book_isbn.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_isbn.title
     *
     * @param title the value for book_isbn.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_isbn.image
     *
     * @return the value of book_isbn.image
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_isbn.image
     *
     * @param image the value for book_isbn.image
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_isbn.author
     *
     * @return the value of book_isbn.author
     *
     * @mbggenerated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_isbn.author
     *
     * @param author the value for book_isbn.author
     *
     * @mbggenerated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_isbn.translator
     *
     * @return the value of book_isbn.translator
     *
     * @mbggenerated
     */
    public String getTranslator() {
        return translator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_isbn.translator
     *
     * @param translator the value for book_isbn.translator
     *
     * @mbggenerated
     */
    public void setTranslator(String translator) {
        this.translator = translator == null ? null : translator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_isbn.publisher
     *
     * @return the value of book_isbn.publisher
     *
     * @mbggenerated
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_isbn.publisher
     *
     * @param publisher the value for book_isbn.publisher
     *
     * @mbggenerated
     */
    public void setPublisher(String publisher) {
        this.publisher = publisher == null ? null : publisher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_isbn.pubdate
     *
     * @return the value of book_isbn.pubdate
     *
     * @mbggenerated
     */
    public Date getPubdate() {
        return pubdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_isbn.pubdate
     *
     * @param pubdate the value for book_isbn.pubdate
     *
     * @mbggenerated
     */
    public void setPubdate(Date pubdate) {
        this.pubdate = pubdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_isbn.binding
     *
     * @return the value of book_isbn.binding
     *
     * @mbggenerated
     */
    public String getBinding() {
        return binding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_isbn.binding
     *
     * @param binding the value for book_isbn.binding
     *
     * @mbggenerated
     */
    public void setBinding(String binding) {
        this.binding = binding == null ? null : binding.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_isbn.price
     *
     * @return the value of book_isbn.price
     *
     * @mbggenerated
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_isbn.price
     *
     * @param price the value for book_isbn.price
     *
     * @mbggenerated
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_isbn.pages
     *
     * @return the value of book_isbn.pages
     *
     * @mbggenerated
     */
    public Short getPages() {
        return pages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_isbn.pages
     *
     * @param pages the value for book_isbn.pages
     *
     * @mbggenerated
     */
    public void setPages(Short pages) {
        this.pages = pages;
    }
}