package site.luoyu.dao.entity;

public class BookTypeinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_typeinfo.BookTypeId
     *
     * @mbggenerated
     */
    private Integer booktypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_typeinfo.BookTypeName
     *
     * @mbggenerated
     */
    private String booktypename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_typeinfo.BookTypeId
     *
     * @return the value of book_typeinfo.BookTypeId
     *
     * @mbggenerated
     */
    public Integer getBooktypeid() {
        return booktypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_typeinfo.BookTypeId
     *
     * @param booktypeid the value for book_typeinfo.BookTypeId
     *
     * @mbggenerated
     */
    public void setBooktypeid(Integer booktypeid) {
        this.booktypeid = booktypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_typeinfo.BookTypeName
     *
     * @return the value of book_typeinfo.BookTypeName
     *
     * @mbggenerated
     */
    public String getBooktypename() {
        return booktypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_typeinfo.BookTypeName
     *
     * @param booktypename the value for book_typeinfo.BookTypeName
     *
     * @mbggenerated
     */
    public void setBooktypename(String booktypename) {
        this.booktypename = booktypename == null ? null : booktypename.trim();
    }
}