package site.luoyu.dao.entity;

public class BookIsbnWithBLOBs extends BookIsbn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_isbn.author_intro
     *
     * @mbggenerated
     */
    private String authorIntro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_isbn.summary
     *
     * @mbggenerated
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_isbn.catalog
     *
     * @mbggenerated
     */
    private String catalog;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_isbn.author_intro
     *
     * @return the value of book_isbn.author_intro
     * @mbggenerated
     */
    public String getAuthorIntro() {
        return authorIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_isbn.author_intro
     *
     * @param authorIntro the value for book_isbn.author_intro
     * @mbggenerated
     */
    public void setAuthorIntro(String authorIntro) {
        this.authorIntro = authorIntro == null ? null : authorIntro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_isbn.summary
     *
     * @return the value of book_isbn.summary
     * @mbggenerated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_isbn.summary
     *
     * @param summary the value for book_isbn.summary
     * @mbggenerated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_isbn.catalog
     *
     * @return the value of book_isbn.catalog
     * @mbggenerated
     */
    public String getCatalog() {
        return catalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_isbn.catalog
     *
     * @param catalog the value for book_isbn.catalog
     * @mbggenerated
     */
    public void setCatalog(String catalog) {
        this.catalog = catalog == null ? null : catalog.trim();
    }
}