package site.luoyu.dao.entity;

import java.util.Date;

public class BookComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_comment.C_id
     *
     * @mbggenerated
     */
    private Integer cId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_comment.Stu_id
     *
     * @mbggenerated
     */
    private Integer stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_comment.isbn
     *
     * @mbggenerated
     */
    private Long isbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_comment.Commentdate
     *
     * @mbggenerated
     */
    private Date commentdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_comment.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_comment.C_id
     *
     * @return the value of book_comment.C_id
     *
     * @mbggenerated
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_comment.C_id
     *
     * @param cId the value for book_comment.C_id
     *
     * @mbggenerated
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_comment.Stu_id
     *
     * @return the value of book_comment.Stu_id
     *
     * @mbggenerated
     */
    public Integer getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_comment.Stu_id
     *
     * @param stuId the value for book_comment.Stu_id
     *
     * @mbggenerated
     */
    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_comment.isbn
     *
     * @return the value of book_comment.isbn
     *
     * @mbggenerated
     */
    public Long getIsbn() {
        return isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_comment.isbn
     *
     * @param isbn the value for book_comment.isbn
     *
     * @mbggenerated
     */
    public void setIsbn(Long isbn) {
        this.isbn = isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_comment.Commentdate
     *
     * @return the value of book_comment.Commentdate
     *
     * @mbggenerated
     */
    public Date getCommentdate() {
        return commentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_comment.Commentdate
     *
     * @param commentdate the value for book_comment.Commentdate
     *
     * @mbggenerated
     */
    public void setCommentdate(Date commentdate) {
        this.commentdate = commentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_comment.content
     *
     * @return the value of book_comment.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_comment.content
     *
     * @param content the value for book_comment.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}