package site.luoyu.dao.entity;

import java.util.Date;

public class Books {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.Book_id
     *
     * @mbggenerated
     */
    private Integer bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.Stu_id
     *
     * @mbggenerated
     */
    private Integer stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.isbn
     *
     * @mbggenerated
     */
    private Long isbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.pictures
     *
     * @mbggenerated
     */
    private String pictures;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.level
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.recommendStar
     *
     * @mbggenerated
     */
    private Integer recommendstar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.publish_date
     *
     * @mbggenerated
     */
    private Date publishDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.BookTypeId
     *
     * @mbggenerated
     */
    private Integer booktypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.typeCode_class
     *
     * @mbggenerated
     */
    private String typecodeClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.price
     *
     * @mbggenerated
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.Book_id
     *
     * @return the value of books.Book_id
     * @mbggenerated
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.Book_id
     *
     * @param bookId the value for books.Book_id
     * @mbggenerated
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.Stu_id
     *
     * @return the value of books.Stu_id
     * @mbggenerated
     */
    public Integer getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.Stu_id
     *
     * @param stuId the value for books.Stu_id
     * @mbggenerated
     */
    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.isbn
     *
     * @return the value of books.isbn
     * @mbggenerated
     */
    public Long getIsbn() {
        return isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.isbn
     *
     * @param isbn the value for books.isbn
     * @mbggenerated
     */
    public void setIsbn(Long isbn) {
        this.isbn = isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.pictures
     *
     * @return the value of books.pictures
     * @mbggenerated
     */
    public String getPictures() {
        return pictures;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.pictures
     *
     * @param pictures the value for books.pictures
     * @mbggenerated
     */
    public void setPictures(String pictures) {
        this.pictures = pictures == null ? null : pictures.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.level
     *
     * @return the value of books.level
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.level
     *
     * @param level the value for books.level
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.recommendStar
     *
     * @return the value of books.recommendStar
     * @mbggenerated
     */
    public Integer getRecommendstar() {
        return recommendstar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.recommendStar
     *
     * @param recommendstar the value for books.recommendStar
     * @mbggenerated
     */
    public void setRecommendstar(Integer recommendstar) {
        this.recommendstar = recommendstar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.publish_date
     *
     * @return the value of books.publish_date
     * @mbggenerated
     */
    public Date getPublishDate() {
        return publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.publish_date
     *
     * @param publishDate the value for books.publish_date
     * @mbggenerated
     */
    public void setPublishDate(Date publishDate) {
        this.publishDate = publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.BookTypeId
     *
     * @return the value of books.BookTypeId
     * @mbggenerated
     */
    public Integer getBooktypeid() {
        return booktypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.BookTypeId
     *
     * @param booktypeid the value for books.BookTypeId
     * @mbggenerated
     */
    public void setBooktypeid(Integer booktypeid) {
        this.booktypeid = booktypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.typeCode_class
     *
     * @return the value of books.typeCode_class
     * @mbggenerated
     */
    public String getTypecodeClass() {
        return typecodeClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.typeCode_class
     *
     * @param typecodeClass the value for books.typeCode_class
     * @mbggenerated
     */
    public void setTypecodeClass(String typecodeClass) {
        this.typecodeClass = typecodeClass == null ? null : typecodeClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.price
     *
     * @return the value of books.price
     * @mbggenerated
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.price
     *
     * @param price the value for books.price
     * @mbggenerated
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.name
     *
     * @return the value of books.name
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.name
     *
     * @param name the value for books.name
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}