package site.luoyu.dao.entity;

public class Classes {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classes.Class_id
     *
     * @mbggenerated
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classes.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classes.Community_id
     *
     * @mbggenerated
     */
    private Integer communityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classes.Class_id
     *
     * @return the value of classes.Class_id
     *
     * @mbggenerated
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classes.Class_id
     *
     * @param classId the value for classes.Class_id
     *
     * @mbggenerated
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classes.name
     *
     * @return the value of classes.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classes.name
     *
     * @param name the value for classes.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classes.Community_id
     *
     * @return the value of classes.Community_id
     *
     * @mbggenerated
     */
    public Integer getCommunityId() {
        return communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classes.Community_id
     *
     * @param communityId the value for classes.Community_id
     *
     * @mbggenerated
     */
    public void setCommunityId(Integer communityId) {
        this.communityId = communityId;
    }
}