package site.luoyu.dao.entity;

public class Community {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.Community_id
     *
     * @mbggenerated
     */
    private Integer communityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.type
     *
     * @mbggenerated
     */
    private Byte type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.Community_id
     *
     * @return the value of community.Community_id
     *
     * @mbggenerated
     */
    public Integer getCommunityId() {
        return communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.Community_id
     *
     * @param communityId the value for community.Community_id
     *
     * @mbggenerated
     */
    public void setCommunityId(Integer communityId) {
        this.communityId = communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.name
     *
     * @return the value of community.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.name
     *
     * @param name the value for community.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.address
     *
     * @return the value of community.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.address
     *
     * @param address the value for community.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.type
     *
     * @return the value of community.type
     *
     * @mbggenerated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.type
     *
     * @param type the value for community.type
     *
     * @mbggenerated
     */
    public void setType(Byte type) {
        this.type = type;
    }
}