package site.luoyu.dao.entity;

import java.util.Date;

public class Orders {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.OrderID
     *
     * @mbggenerated
     */
    private String orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.Stu_id
     *
     * @mbggenerated
     */
    private Integer stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.totalMoney
     *
     * @mbggenerated
     */
    private Float totalmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderDate
     *
     * @mbggenerated
     */
    private Date orderdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.OrderID
     *
     * @return the value of orders.OrderID
     * @mbggenerated
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.OrderID
     *
     * @param orderid the value for orders.OrderID
     * @mbggenerated
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.Stu_id
     *
     * @return the value of orders.Stu_id
     * @mbggenerated
     */
    public Integer getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.Stu_id
     *
     * @param stuId the value for orders.Stu_id
     * @mbggenerated
     */
    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.totalMoney
     *
     * @return the value of orders.totalMoney
     * @mbggenerated
     */
    public Float getTotalmoney() {
        return totalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.totalMoney
     *
     * @param totalmoney the value for orders.totalMoney
     * @mbggenerated
     */
    public void setTotalmoney(Float totalmoney) {
        this.totalmoney = totalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orderDate
     *
     * @return the value of orders.orderDate
     * @mbggenerated
     */
    public Date getOrderdate() {
        return orderdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orderDate
     *
     * @param orderdate the value for orders.orderDate
     * @mbggenerated
     */
    public void setOrderdate(Date orderdate) {
        this.orderdate = orderdate;
    }
}