package site.luoyu.dao.entity;

public class UserStudent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_student.Stu_id
     *
     * @mbggenerated
     */
    private Integer stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_student.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_student.nickname
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_student.phoneNumber
     *
     * @mbggenerated
     */
    private String phonenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_student.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_student.Community_id
     *
     * @mbggenerated
     */
    private Integer communityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_student.classes
     *
     * @mbggenerated
     */
    private Integer classes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_student.portrait
     *
     * @mbggenerated
     */
    private String portrait;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_student.passwd
     *
     * @mbggenerated
     */
    private String passwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_student.Stu_id
     *
     * @return the value of user_student.Stu_id
     * @mbggenerated
     */
    public Integer getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_student.Stu_id
     *
     * @param stuId the value for user_student.Stu_id
     * @mbggenerated
     */
    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_student.name
     *
     * @return the value of user_student.name
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_student.name
     *
     * @param name the value for user_student.name
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_student.nickname
     *
     * @return the value of user_student.nickname
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_student.nickname
     *
     * @param nickname the value for user_student.nickname
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_student.phoneNumber
     *
     * @return the value of user_student.phoneNumber
     * @mbggenerated
     */
    public String getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_student.phoneNumber
     *
     * @param phonenumber the value for user_student.phoneNumber
     * @mbggenerated
     */
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber == null ? null : phonenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_student.email
     *
     * @return the value of user_student.email
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_student.email
     *
     * @param email the value for user_student.email
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_student.Community_id
     *
     * @return the value of user_student.Community_id
     * @mbggenerated
     */
    public Integer getCommunityId() {
        return communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_student.Community_id
     *
     * @param communityId the value for user_student.Community_id
     * @mbggenerated
     */
    public void setCommunityId(Integer communityId) {
        this.communityId = communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_student.classes
     *
     * @return the value of user_student.classes
     * @mbggenerated
     */
    public Integer getClasses() {
        return classes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_student.classes
     *
     * @param classes the value for user_student.classes
     * @mbggenerated
     */
    public void setClasses(Integer classes) {
        this.classes = classes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_student.portrait
     *
     * @return the value of user_student.portrait
     * @mbggenerated
     */
    public String getPortrait() {
        return portrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_student.portrait
     *
     * @param portrait the value for user_student.portrait
     * @mbggenerated
     */
    public void setPortrait(String portrait) {
        this.portrait = portrait == null ? null : portrait.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_student.passwd
     *
     * @return the value of user_student.passwd
     * @mbggenerated
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_student.passwd
     *
     * @param passwd the value for user_student.passwd
     * @mbggenerated
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }
}